// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyACdgQcVuTrZ6K6BAjOFnbY-tcLPZjIvvw',
    appId: '1:329867258065:web:e4a65647e6517c47e23df0',
    messagingSenderId: '329867258065',
    projectId: 'my-ecommerce-app-123-58241',
    authDomain: 'my-ecommerce-app-123-58241.firebaseapp.com',
    storageBucket: 'my-ecommerce-app-123-58241.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDNBsrLIYpb-uXjSq3njKbKsPCa57qwdYg',
    appId: '1:329867258065:android:f62a9d45e500518ce23df0',
    messagingSenderId: '329867258065',
    projectId: 'my-ecommerce-app-123-58241',
    storageBucket: 'my-ecommerce-app-123-58241.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC3G-X74XlzgNN_UEodpiyTj3qbA82LP5M',
    appId: '1:329867258065:ios:775612095221f90de23df0',
    messagingSenderId: '329867258065',
    projectId: 'my-ecommerce-app-123-58241',
    storageBucket: 'my-ecommerce-app-123-58241.firebasestorage.app',
    iosBundleId: 'com.example.ecommerceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC3G-X74XlzgNN_UEodpiyTj3qbA82LP5M',
    appId: '1:329867258065:ios:775612095221f90de23df0',
    messagingSenderId: '329867258065',
    projectId: 'my-ecommerce-app-123-58241',
    storageBucket: 'my-ecommerce-app-123-58241.firebasestorage.app',
    iosBundleId: 'com.example.ecommerceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyACdgQcVuTrZ6K6BAjOFnbY-tcLPZjIvvw',
    appId: '1:329867258065:web:ab6d1f3060211880e23df0',
    messagingSenderId: '329867258065',
    projectId: 'my-ecommerce-app-123-58241',
    authDomain: 'my-ecommerce-app-123-58241.firebaseapp.com',
    storageBucket: 'my-ecommerce-app-123-58241.firebasestorage.app',
  );
}
